<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/osbbook_ejb/AdapterSOAProject/FindCustomer" name="FindCustomer-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/osbbook_ejb/AdapterSOAProject/FindCustomer" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/osbbook_ejb/AdapterSOAProject/FindCustomer" location="../adapter/AdapterSOAProject/FindCustomer.wsdl"/>
  <binding name="FindCustomer_ptt-binding" type="tns:FindCustomer_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="FindCustomerSelect">
      <soap:operation soapAction="FindCustomerSelect"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="FindCustomer-service">
    <port name="FindCustomer-port" binding="tns:FindCustomer_ptt-binding">
      <soap:address location="jca://eis/DB/OsbCookbookConnection"/>
    </port>
  </service>
</definitions>