<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions
     name="CustomerManagementAsync"
     targetNamespace="http://osb-cookbook/CustomerManagementAsync"
     xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/"
     xmlns:WL5G3N1="http://osb-cookbook/CustomerManagementAsync"
    >
    <WL5G3N0:types>
        <xsd:schema targetNamespace="http://osb-cookbook/CustomerManagementAsync" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:WL5G3N4="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:cus="http://osb-cookbook/customer"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://osb-cookbook/CustomerManagementAsync"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://osb-cookbook/customer" schemaLocation="http://127.0.0.1:7001/sbresource?PROXY%2Finvoking-osb-service-async-from-sca-composite%2Fproxy%2FCustomerManagementAsync%3ASCHEMA%2Finvoking-osb-service-async-from-sca-composite%2Fxsd%2FCustomer"/>
            <xsd:element name="FindCustomer">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="ID" type="xsd:long"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="FindCustomerResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Customer" type="cus:CustomerTyp"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </WL5G3N0:types>
    <WL5G3N0:message name="FindCustomerResponse">
        <WL5G3N0:part name="parameters" element="WL5G3N1:FindCustomerResponse"/>
    </WL5G3N0:message>
    <WL5G3N0:message name="FindCustomerRequest">
        <WL5G3N0:part name="parameters" element="WL5G3N1:FindCustomer"/>
    </WL5G3N0:message>
    <WL5G3N0:portType name="CustomerManagementAsyncCallback">
        <WL5G3N0:operation name="FindCustomerResponseAsync">
            <WL5G3N0:input message="WL5G3N1:FindCustomerResponse"/>
        </WL5G3N0:operation>
    </WL5G3N0:portType>
    <WL5G3N0:portType name="CustomerManagementAsync">
        <WL5G3N0:operation name="FindCustomerAsync">
            <WL5G3N0:input message="WL5G3N1:FindCustomerRequest"/>
        </WL5G3N0:operation>
    </WL5G3N0:portType>
    <WL5G3N0:binding name="CustomerManagementSOAPAsyncCallback" type="WL5G3N1:CustomerManagementAsyncCallback">
        <WL5G3N2:binding style="document" transport="http://xmlns.oracle.com/soa/direct"/>
        <WL5G3N0:operation name="FindCustomerResponseAsync">
            <WL5G3N2:operation soapAction="http://osb-cookbook/CustomerManagement/FindCustomerResponse"/>
            <WL5G3N0:input>
                <WL5G3N2:body use="literal"/>
            </WL5G3N0:input>
        </WL5G3N0:operation>
    </WL5G3N0:binding>
    <WL5G3N0:binding name="CustomerManagementSOAPAsync" type="WL5G3N1:CustomerManagementAsync">
        <WL5G3N2:binding style="document" transport="http://www.bea.com/transport/2007/05/sb"/>
        <WL5G3N0:operation name="FindCustomerAsync">
            <WL5G3N2:operation soapAction="http://osb-cookbook/CustomerManagement/FindCustomer"/>
            <WL5G3N0:input>
                <WL5G3N2:body use="literal"/>
            </WL5G3N0:input>
        </WL5G3N0:operation>
    </WL5G3N0:binding>
    <WL5G3N0:service name="CustomerManagementSOAPAsyncQSService">
        <WL5G3N0:port name="CustomerManagementSOAPAsyncQSPort" binding="WL5G3N1:CustomerManagementSOAPAsync">
            <WL5G3N2:address location="sb://192.168.219.135:7001/CustomerManagementAsyncCallback"/>
        </WL5G3N0:port>
    </WL5G3N0:service>
</WL5G3N0:definitions>
