package wsrm.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://localhost:7001/using-reliable-msg-with-ws-transport/Provider?wsdl",
  targetNamespace="http://wsrm.osbbook", name="HelloWorldService")
@XmlSeeAlso(
  { wsrm.types.ObjectFactory.class })
public interface HelloWorldService
{
  @WebMethod
  @Action(input="http://wsrm.osbbook/HelloWorldService/sayHelloOneWay")
  @RequestWrapper(localName="sayHelloOneWay", targetNamespace="http://wsrm.osbbook",
    className="wsrm.types.SayHelloOneWay")
  @Oneway
  public void sayHelloOneWay();
}
